apiVersion: v1
kind: Pod
metadata:
  name: todo-app
spec:
  containers:
    - name: todo
      image: pavangowda111/todo-app:1.0
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"

