apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PAVANBK007/argocd.git'
    targetRevision: HEAD
    path: dev  # folder where deployment.yaml and service.yaml are
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
